name: "Sheriff Apply"
description: "Perform a Sheriff apply from GitHub releases"
author: "Craig Anderson"
inputs:
  configDir:
    description: "location of config files"
    required: true
  mode:
    description: "resources, groups or entra"
    required: true
  planOnly:
    description: "Plan only, do not apply"
    default: 'false'
    required: false
  subscriptionId:
    description: "Azure subscription ID"
    required: true
  clientId:
    description: "Azure client ID"
    required: true
  tenantId:
    description: "Azure tenant ID"
    required: true
  clientSecret:
    description: "Azure client secret"
    required: false
  authScheme:
    description: "Authentication scheme to use: 'federated' for OIDC federated credentials, or 'sp' for Service Principal."
    required: false
    default: "federated"
branding:
  icon: "archive"
  color: "green"
runs:
  using: "node20"
  main: "dist/index.js"
