name: "Sheriff Apply"
description: "Perform a Sheriff apply from GitHub releases"
author: "Craig Anderson"
inputs:
  configDir:
    description: "location of config files"
    required: true
  mode:
    description: "Resources or groups"
    required: true
  planOnly:
    description: "Plan only, do not apply"
    default: 'false'
    required: false
  subscriptionId:
    description: "Azure subscription ID"
    required: true
branding:
  icon: "archive"
  color: "green"
runs:
  using: "node20"
  main: "dist/index.js"
