---
name: build

on:
  workflow_call:
    inputs:
      version:
        required: false
        default: "v0.0.0"
        type: string
    outputs:
      is_pre_release:
        value: ${{ jobs.build.outputs.is_pre_release }}
      node_version:
        value: ${{ jobs.build.outputs.node_version }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      is_pre_release: ${{ steps.build.outputs.is_pre_release }}
      node_version: ${{ steps.get_node_version.outputs.node_version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - run: npm ci
      - run: npm test
      - id: build
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: "${{ github.workspace }}/dist/"
          if-no-files-found: error
      - id: get_node_version
        run: |
          node_version=$(cat "${GITHUB_WORKSPACE}/.nvmrc")
          echo "node_version=${node_version}" >> "$GITHUB_OUTPUT"
