---
name: Release

on:
  push:
    tags:
      - "*"

jobs:
  preflight:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - id: get_version
        run: echo "version=${GITHUB_REF#refs/*/}" >> "$GITHUB_OUTPUT"
  build:
    uses: ./.github/workflows/build.yml
    needs: preflight
    with:
      version: ${{ needs.preflight.outputs.version }}
  release:
    runs-on: ubuntu-latest
    needs:
      - preflight
      - build
    steps:
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: dist
          path: ${{ github.workspace }}
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: ${{ needs.build.outputs.is_pre_release }}
